### ISSUE TITLE
Manage users

### ISSUE THREAD

**Issue by snapiz** [gomada/gomada#14]
As admin, I can manage users so that I can invite, edit, delete and disable them.

### Service
- [x] Implement updateUser mutation #22
- [x] Implement deleteUser mutation #23
- [x] Implement updateUserState mutation #24
- [x] Implement users root query #25

### Web
- [x] Implement UserList page #26 
- [x] Implement UserEdit page #27
