### ISSUE TITLE
Manage contacts by lists

### ISSUE THREAD

**Issue by snapiz** [gomada/gomada#8]
As user, I want to manage my contacts.

### Service
- [x] Create lists table SQL migration file #35
- [x] Create warehouses table SQL migration file #57 
- [x] Create list_fields table SQL migration file #55
- [x] Create WarehouseType #58 
- [x] Create ListType #37
- [x] Create ContactType #38
- [x] Create ListFieldType #56 
- [x] Implement me.lists query #39
- [x] Implement me.lists.fileds query #54 
- [x] Implement me.lists.contacts query #40
- [x] Implement createWarehouse mutation #59
- [x] Implement updateWarehouse mutation #60
- [x] Implement deleteWarehouse mutation #61
- [x] Implement createList mutation #41
- [x] Implement updateList mutation #42
- [x] Implement deleteList mutation #43
- [x] Implement addContacts mutation #44
- [x] Implement removeContacts mutation #46

### Web
- [x] Implement ListList page #50
- [x] Implement ListEdit page #51
- [x] Implement WarehouseList page #62
- [x] Implement WarehouseEdit page #63
- [x] Implement WarehouseEditListList page #64
